name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: yarn install

      - name: Test the app and build
        run: |
          yarn test
          yarn build

      - name: Publish builded content to GitHub Pages
        uses: rame0/github-pages-deploy-action@3.7.1
        with:
          FOLDER: build
          BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CLEAN: true