name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1
      
      - name: Install dependencies
        uses: yarn install --frozen-lockfile
        
      - name: Test the app
        uses: yarn test
        
      - name: Generate your awesome content
        run: yarn buld
      
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: build
          branch: gh-pages
          token: ${{ secrets.ACCESS_TOKEN }}
